[build]
  publish = "public"
  command = "npm run init && npm run build" # do npm run init && npm run build on first build.
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
